// <auto-generated />
using System;
using HotelOS.Identity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelOS.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260525063308_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("accounts", null, t =>
                        {
                            t.Property("role")
                                .HasColumnName("role1");
                        });

                    b.HasDiscriminator<string>("role").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.StaffProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_title");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("staff_profiles", (string)null);
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.CleaningStaff", b =>
                {
                    b.HasBaseType("HotelOS.Identity.Core.Entities.Account");

                    b.Property<string>("CurrentAssignment")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("current_assignment");

                    b.Property<Guid?>("ProfileId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("staff_id");

                    b.HasIndex("ProfileId");

                    b.ToTable("accounts", t =>
                        {
                            t.Property("role")
                                .HasColumnName("role1");
                        });

                    b.HasDiscriminator().HasValue("CleaningStaff");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.Client", b =>
                {
                    b.HasBaseType("HotelOS.Identity.Core.Entities.Account");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<int>("LoyaltyPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("loyalty_points");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("PreferredPaymentMethod")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("preferred_payment_method");

                    b.ToTable("accounts", t =>
                        {
                            t.Property("role")
                                .HasColumnName("role1");
                        });

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.KitchenStaff", b =>
                {
                    b.HasBaseType("HotelOS.Identity.Core.Entities.Account");

                    b.Property<Guid?>("ProfileId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("staff_id");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("station");

                    b.HasIndex("ProfileId");

                    b.ToTable("accounts", t =>
                        {
                            t.Property("role")
                                .HasColumnName("role1");
                        });

                    b.HasDiscriminator().HasValue("KitchenStaff");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.MaintenanceStaff", b =>
                {
                    b.HasBaseType("HotelOS.Identity.Core.Entities.Account");

                    b.Property<Guid?>("ProfileId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialization");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("staff_id");

                    b.HasIndex("ProfileId");

                    b.ToTable("accounts", t =>
                        {
                            t.Property("role")
                                .HasColumnName("role1");
                        });

                    b.HasDiscriminator().HasValue("MaintenanceStaff");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.Manager", b =>
                {
                    b.HasBaseType("HotelOS.Identity.Core.Entities.Account");

                    b.Property<int>("AccessLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("access_level");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<Guid?>("ProfileId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("staff_id");

                    b.HasIndex("ProfileId");

                    b.ToTable("accounts", t =>
                        {
                            t.Property("role")
                                .HasColumnName("role1");
                        });

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.Receptionist", b =>
                {
                    b.HasBaseType("HotelOS.Identity.Core.Entities.Account");

                    b.Property<string>("DeskNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("desk_number");

                    b.Property<Guid?>("ProfileId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("shift");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("staff_id");

                    b.HasIndex("ProfileId");

                    b.ToTable("accounts", t =>
                        {
                            t.Property("role")
                                .HasColumnName("role1");
                        });

                    b.HasDiscriminator().HasValue("Receptionist");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.Server", b =>
                {
                    b.HasBaseType("HotelOS.Identity.Core.Entities.Account");

                    b.Property<Guid?>("ProfileId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("staff_id");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zone");

                    b.HasIndex("ProfileId");

                    b.ToTable("accounts", t =>
                        {
                            t.Property("role")
                                .HasColumnName("role1");
                        });

                    b.HasDiscriminator().HasValue("Server");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.StaffProfile", b =>
                {
                    b.OwnsOne("HotelOS.Identity.Core.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("StaffProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("state");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("street_address");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("zip_code");

                            b1.HasKey("StaffProfileId");

                            b1.ToTable("staff_profiles");

                            b1.WithOwner()
                                .HasForeignKey("StaffProfileId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.CleaningStaff", b =>
                {
                    b.HasOne("HotelOS.Identity.Core.Entities.StaffProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.Client", b =>
                {
                    b.OwnsOne("HotelOS.Identity.Core.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("state");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("street_address");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("zip_code");

                            b1.HasKey("ClientId");

                            b1.ToTable("accounts");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.KitchenStaff", b =>
                {
                    b.HasOne("HotelOS.Identity.Core.Entities.StaffProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.MaintenanceStaff", b =>
                {
                    b.HasOne("HotelOS.Identity.Core.Entities.StaffProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.Manager", b =>
                {
                    b.HasOne("HotelOS.Identity.Core.Entities.StaffProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.Receptionist", b =>
                {
                    b.HasOne("HotelOS.Identity.Core.Entities.StaffProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("HotelOS.Identity.Core.Entities.Server", b =>
                {
                    b.HasOne("HotelOS.Identity.Core.Entities.StaffProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
